package com.jake.fitnessapi.service;

import com.jake.fitnessapi.model.Workout;
import com.jake.fitnessapi.repository.WorkoutRepository;
import org.springframework.stereotype.Service;

import java.util.List;

// Service class that handles workout-related logic
@Service
public class WorkoutService {

    // Repository handles database operations (replaces in-memory list)
    private final WorkoutRepository workoutRepository;

    // Constructor injection for repository
    public WorkoutService(WorkoutRepository workoutRepository) {
        this.workoutRepository = workoutRepository;
    }

    // Returns all workouts from the database
    public List<Workout> getWorkouts() {
        return workoutRepository.findAll();
    }

    // Creates a new workout and saves it to the database
    public Workout createWorkout(Workout workout) {
        // ID is auto-generated by the database now
        return workoutRepository.save(workout);
    }
}
