package com.jake.fitnessapi.model;

import java.time.LocalDate;
import java.util.UUID;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;

// Model class that represents a workout in the application
public class Workout {

    // Unique ID for each workout (generated by the server)
    private UUID id;

    // Name of the workout (cannot be empty)
    @NotBlank
    private String name;

    // Date the workout took place or is scheduled
    @NotNull
    private LocalDate date;

    // No-argument constructor
    // Needed for Spring when mapping JSON to this object
    public Workout() {}

    // Constructor used when creating a workout with all values
    public Workout(UUID id, String name, LocalDate date) {
        this.id = id;
        this.name = name;
        this.date = date;
    }

    public UUID getId() {
        return id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public LocalDate getDate() {
        return date;
    }

    public void setDate(LocalDate date) {
        this.date = date;
    }
}
